[build]
  command = "yarn run build"
  functions = "src/functions"
  publish = "/build"

[dev]
  framework = "create-react-app" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200